services:
  postgres:
    image: postgres:16
    container_name: pdi-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdi_main_db
    ports:
      - "5432:5432"
    volumes:
      - pdi_postgres_data:/var/lib/postgresql/data
      - ./docker/init/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - pdi-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pdi-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pdi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pdi-network

volumes:
  pdi_postgres_data:

networks:
  pdi-network:
    driver: bridge